### ISSUE TITLE
Shell hangs when calling Zone SetAllVelocity in MS_RUN

### ISSUE THREAD

**Issue by giantlol** [Beckhoff-USA-Community/XTS_Base#44]
I see this issue in release 1.3.1, but not in 1.2.8.  

My setup only has 4 Zones (no other objectives) where I want to have specified velocities for all the movers currently within those zones. 

To reproduce, comment out all other objectives from the sample MAIN leaving just the zones.  Also get rid of all the routing logic under MS_RUN.  In MS_ENABLED, change the Zone starting commands to velocity moves:

```
Zone[0].CurrentMoverList.MoveAllVelocity(lowVelocity); //.MoveAllToStation(Station[0]);
Zone[1].CurrentMoverList.MoveAllVelocity(mediumVelocity); //.MoveAllToStation(Station[0]);
Zone[2].CurrentMoverList.MoveAllVelocity(highVelocity); //.MoveAllToStation(Station[0]);
Zone[3].CurrentMoverList.MoveAllVelocity(mediumVelocity); //.MoveAllToStation(Station[0]);
```

In this state, all the movers take off from their starting positions just fine, but they keep the velocities of their current zones wherever the program is started, and don't update as they move.  When I add this to the MS_RUN state to get that behavior, my XaeShell hangs:

```
Zone[0].CurrentMoverList.SetAllVelocity(lowVelocity);
Zone[1].CurrentMoverList.SetAllVelocity(mediumVelocity);
Zone[2].CurrentMoverList.SetAllVelocity(highVelocity);
Zone[3].CurrentMoverList.SetAllVelocity(mediumVelocity);
```

I need to set my System to Config mode to regain control of the TcXaeShell.  I'm not well versed with the platform so I'm not sure how to debug from there.

**Comment by pswift066** [comment]
I think what you mean to be instructing the movers to do is: "for any mover in the zone, move at a specified velocity."
Instead what this code would do is: "Issue new MC_MoveVelocity commands every single cycle for all movers in the Zone."

Instead of using Zones this way, I would recommend configuring PositionTriggers at the beginning of every speed-control region. That way every mover only receives a MC_MoveVelocity command once upon entry, and not continuously.

**Comment by pswift066** [comment]
I agree with the last statement and will investigate. My hunch is that the computational load on the motion control is not the issue- but rather it is gumming up ADS by submitting so many Event Logger entries. Each motion command triggers one. That may explain why XAE hangs.

One alternative could be to feed the velocity values into a virtual axis via External Setpoint Generator, and then gearing movers to that virtual axis. 

In general I can say that this example project was written with the intent that motion commands be called once, and not continuously. This is a recommendation we make in the Quick Tips section of the docs:
https://beckhoff-usa-community.github.io/XTS_Base/GettingStarted/QuickTips.html

That being said, your approach may very well be viable- it just treads over less-well-tested ground in the application. As you said, it sounds like it functioned in a previous version. We will take a look.

My professional email is p.swift@beckhoff.com. If it makes sense to schedule a call, please reach out. I'm on Central Standard Time.
