### ISSUE TITLE
Station Extra Example Code Documentation

### ISSUE THREAD

**Issue by grantbeebe24** [Beckhoff-USA-Community/XTS_Base#51]
Station Documentation Page Link:
https://beckhoff-usa-community.github.io/XTS_Base/CodeReference/Station.html

Code will no longer compile, Received Error It is not possible to perform component access '.', index access '[]' or call '()' on result of function call. Assign result to help variable first.	

Example Code Issue from Documentation
// Immediately redirect all incoming shuttles to Station 1 instead of Station 0
FOR i := 0 TO Station[0].TrackedMoverCount-1 DO
    Station[0].TrackedMovers[i]^.MoveToStation( Station[1] );
END_FOR

**Comment by netbymatt** [comment]
This has been addressed in f3a479feb1b8f22c1915052ece0feaa07eb77cf6. But not published to the documentation page at this time.
