### ISSUE TITLE
Error ID not publishing for MC_GroupReset function block

### ISSUE THREAD

**Issue by zacharybob** [Beckhoff-USA-Community/XTS_Base#53]
In line 226 the base code copyies in fbGroupStatus.ErrorId on both if/elsif statements. The elsif for fbGroupReset.Error should copy the fbGroupReset.ErrorId instead. Suggested fix in screenshot.
![image](https://github.com/Beckhoff-USA-Community/XTS_Base/assets/168679623/4dbc8f42-f596-4286-b5c0-c2c3a47bbd2d)

**Comment by netbymatt** [comment]
Thank you for the feedback on this missing group reset error id. We've addressed this in our feature branch (commit 72c1466) which will be released soon in the main branch.
https://github.com/Beckhoff-USA-Community/XTS_Base/blob/ddb90f051b2c706a131a3e28269f2ad285c93a1c/Base%20Project/Main/POUs/XTS/Administrative/Mediator.TcPOU#L426-L438
One of the fixes addressed in the feature branch is a problem that may have led you to line 226. The main branch uses code where every mover will try to call a group reset when necessary. This is successful up to a point, but with a lot of movers becomes unreliable. The new branch uses a new System object to manage functionality that addresses all movers simultaneously.
