### ISSUE TITLE
Issue with reset the mover If they have any error.

### ISSUE THREAD

**Issue by phucpha** [Beckhoff-USA-Community/XTS_Base#54]
![image](https://github.com/Beckhoff-USA-Community/XTS_Base/assets/91473316/4be6ade3-3f93-4a91-a311-678b055cb937)
when a mover have an error, i want it reset by call mover.enable(). but in its method not reset the mover. The "internalEnable" = true will call MC_reset in fb mover but when mover error, the method enable can't set the  "internalEnable" = true

**Comment by netbymatt** [comment]
This is addressed the the feature/mediator branch commits c93d2b9f958755ed444aefdb413f1c0186f7589e 0cae6e2b8cc59eec2266fa45c1ffc2a8db234775
